# config/xbox_teleop.yaml
teleop_twist_joy_node:
  ros__parameters:
    axis_linear.x: 1        # left stick vertical
    scale_linear.x: 1.0
    scale_linear_turbo.x: 2.0

    axis_angular.yaw: 0     # left stick horizontal
    scale_angular.yaw: 2.0
    scale_angular_turbo.yaw: 2.0

    enable_button: 5        # RB to enable
    enable_turbo_button: 7  # RT for turbo

