autonomy_behaviour:
  ros__parameters:
    settle_time_s: 10.0
    scan_time_s: 3.0
    confirm_range: 8.0
    batch_size: 4
    lidar_max_m: 12.0
    room_radius_m: 0.0
    room_polygon_xy: '[]'
    min_separation_m: 2.0
    furthest_bias: true
    joy_rb_index: 5
