# Timing consistency
- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

# Position of joints [ie. wheels] (published by ignition::gazebo::systems::JointStatePublisher)
- ros_topic_name: '/joint_states'
  gz_topic_name: '/model/husky/joint_states'
  ros_type_name: 'sensor_msgs/msg/JointState'
  gz_type_name: 'ignition.msgs.Model'
  direction: GZ_TO_ROS

# Odometry (use the WITH-COVARIANCE topic from Gazebo)
- ros_topic_name: '/odometry'
  gz_topic_name: '/model/husky/odometry_with_covariance'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name: 'gz.msgs.OdometryWithCovariance'
  direction: GZ_TO_ROS

# Inertial Measurement Unit
- ros_topic_name: '/imu'
  gz_topic_name: '/model/husky/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'ignition.msgs.IMU'
  direction: GZ_TO_ROS

# Command velocity
- ros_topic_name: '/cmd_vel'
  gz_topic_name: '/model/husky/cmd_vel'
  ros_type_name: 'geometry_msgs/msg/Twist'
  gz_type_name: 'ignition.msgs.Twist'
  direction: ROS_TO_GZ

# Lidar: laserscan
- ros_topic_name: "/scan"
  gz_topic_name: "/model/husky/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# Lidar: pointcloud
- ros_topic_name: "/scan/points"
  gz_topic_name: "/model/husky/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# Camera: RGB
- ros_topic_name: "/camera/image"
  gz_topic_name: "/model/husky/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# Camera: depth
- ros_topic_name: "/camera/depth/image"
  gz_topic_name: "/model/husky/camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# Camera: depth pointcloud
- ros_topic_name: "/camera/depth/points"
  gz_topic_name: "/model/husky/camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# # Camera: info
# - ros_topic_name: "/camera/info"
#   gz_topic_name: "/model/husky/camera/info"
#   ros_type_name: "sensor_msgs/msg/CameraInfo"
#   gz_type_name: "ignition.msgs.CameraInfo"
#   direction: GZ_TO_ROS    

# # GPS
# - ros_topic_name: "/gps/fix"
#   gz_topic_name: "/model/husky/gps"
#   ros_type_name: "sensor_msgs/msg/NavSatFix" 
#   gz_type_name: "ignition.msgs.Gps"
#   direction: GZ_TO_ROS

# # GPS velocity
# - ros_topic_name: "/gps/vel"
#   gz_topic_name: "/model/husky/gps/vel"
#   ros_type_name: "geometry_msgs/msg/TwistStamped" 
#   gz_type_name: "ignition.msgs.Twist"
#   direction: GZ_TO_ROS  

# # Battery state
# - ros_topic_name: "/battery_state"
#   gz_topic_name: "/model/husky/battery_state"
#   ros_type_name: "sensor_msgs/msg/BatteryState" 
#   gz_type_name: "ignition.msgs.BatteryState"      
#   direction: GZ_TO_ROS

# # Magnetic field (compass)
# - ros_topic_name: "/magnetic_field"
#   gz_topic_name: "/model/husky/magnetic_field"
#   ros_type_name: "sensor_msgs/msg/MagneticField" 
#   gz_type_name: "ignition.msgs.MagneticField"      
#   direction: GZ_TO_ROS

# # Air pressure (barometer)
# - ros_topic_name: "/air_pressure"
#   gz_topic_name: "/model/husky/air_pressure"
#   ros_type_name: "sensor_msgs/msg/FluidPressure" 
#   gz_type_name: "ignition.msgs.FluidPressure"      
#   direction: GZ_TO_ROS  

# # Temperature
# - ros_topic_name: "/temperature"
#   gz_topic_name: "/model/husky/temperature"
#   ros_type_name: "sensor_msgs/msg/Temperature" 
#   gz_type_name: "ignition.msgs.Temperature"     
#   direction: GZ_TO_ROS          

# i added a bunch of sensors but they are not used currently so commented them out, we wanted to do battery management but we realized its not super relevant for simulation right now.