---
# Joint states (Ignition -> ROS)
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/world_demo/model/X4/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS

# Dynamic TFs (Ignition -> ROS)
- ros_topic_name: "/tf"
  gz_topic_name: "/world/world_demo/dynamic_frame_tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

# Static TFs (Ignition -> ROS) — map ignition static frames to /tf_static
- ros_topic_name: "/tf_static"
  gz_topic_name: "/world/world_demo/static_frame_tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "ignition.msgs.Pose_V"
  direction: GZ_TO_ROS

# Cmd_vel → odometry
- ros_topic_name: "/X4/cmd_vel"
  gz_topic_name: "/X4/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/X4/odom"
  gz_topic_name: "/model/X4/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS


# IMU, GPS, LIDAR, RGBD camera → sensors data
- ros_topic_name: "/X4/imu"
  gz_topic_name: "/X4/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/X4/gps"
  gz_topic_name: "/X4/gps"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "ignition.msgs.NavSat"
  direction: GZ_TO_ROS

- ros_topic_name: "/X4/scan"
  gz_topic_name: "/X4/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS

# - ros_topic_name: "/X4/rgbd"
#   gz_topic_name: "/X4/rgbd"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "ignition.msgs.Image"
#   direction: GZ_TO_ROS

# Lidar: pointcloud
- ros_topic_name: "/X4/scan/points"
  gz_topic_name: "/X4/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS

# Camera: RGB
- ros_topic_name: "/X4/camera/image"
  gz_topic_name:  "/X4/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# Camera: depth
- ros_topic_name: "/X4/camera/depth/image"
  gz_topic_name: "X4/camera/depth/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS

# Camera: depth pointcloud
- ros_topic_name: "/X4/camera/depth/points"
  gz_topic_name: "/X4/camera/depth/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
